---
deployment:
  tasks:
    - export DEPLOYPATH=/home/user/public_html/
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp datenschutz.html $DEPLOYPATH
    - /bin/cp impressum.html $DEPLOYPATH